### ISSUE TITLE
Request: expose a port/endpoint for healthchecks

### ISSUE THREAD

**Issue by jonadaly** [celery/kombu#1177]
### Summary
It would be helpful if apps using kombu were able to expose a port and/or endpoint for the purposes of healthchecks and monitoring. For example, a GET request to `http://localhost:8080/running` might give a response of `200 - {"running": true}` while a kombu consumer is running.

### Use cases

When running apps in kubernetes, it's useful to be able to expose an endpoint for monitoring purposes (https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/). For example, as part of a k8s deployment you might have:

```
containers:
      - name: my-container
        image: myimage:latest
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /running
            port: 8080
        readinessProbe:
          httpGet:
            path: /running
            port: 8080
```

If the app crashes, kubernetes would then know to terminate the pod and bring up a new one.

Healthcheck or monitoring endpoints are also useful for situations where you need to know when an app running in a container is ready, for example in docker-compose stacks.

### Proposal
The proposal is for kombu to stand up an HTTP endpoint, which returns an "OK" status code on being hit with an HTTP request, while a consumer is listening. This port would be used externally to monitor whether the app is still consuming.

If I have missed some functionality of kombu which could be used as an alternative, please let me know - I haven't found anything in the documentation.

**Comment by jonadaly** [comment]
Would be interested to hear anyone's thoughts on this idea, or an alternative suggestion for monitoring!

**Comment by NoyGri** [comment]
@jonadaly  I'm not sure I'd go with an HTTP endpoint, it could create an unnecessary security risk. I would just like a way for my consumer to be able to observe **heartbeat pulses** and **Connection disruptions**.

Right now I've implemented a `ConsumerMixin` child class, and I've implemented the following callbacks:
* `on_connection_revived` - create a file at `/some/path/alive.txt`
* `on_consume_ready` - create a file at `/some/path/alive.txt`
* `on_connection_error` - delete a file at `/some/path/alive.txt`
* `on_consume_end` - shut down pod

Then both my probes look for that file to know when the service is alive
```
livenessProbe/readinessProbe:
            exec:
              command:
                - cat
                - /some/path/alive.txt
```

It's terribly hacky and actually, I still haven't gotten the `on_connection_error` and `on_consume_end` callbacks to be called.
